import { initCounter } from './counter';
import { initBoot } from './boot';
import { initNav } from './nav';
import { initCursor } from './cursor';
import { initDisk } from './disk';
import { initKonami } from './konami';
import { initSaver } from './saver';
import { initVu } from './vu';
import { initDoc } from './doc';
import { initTape } from './tape';
import { initKeys } from './keys';
import { initErr } from './err';
import { initHandheld } from './handheld';
import { initLive } from './live';

initCounter();
initBoot();
initNav();
initCursor();
initDisk();
initKonami();
initSaver();
initVu();
initDoc();
initTape();
initKeys();
initErr();
initHandheld();
initLive();
