import { initCounter } from './counter';
import { initBoot } from './boot';
import { initNav } from './nav';
import { initKnob } from './knob';
import { initCursor } from './cursor';
import { initDisk } from './disk';
import { initPads } from './pads';
import { initKonami } from './konami';
import { initSaver } from './saver';
import { initVu } from './vu';
import { initDoc } from './doc';
import { initTape } from './tape';
import { initSnd } from './snd';
import { initKeys } from './keys';
import { initErr } from './err';

initCounter();
initBoot();
initNav();
initKnob();
initCursor();
initDisk();
initPads();
initKonami();
initSaver();
initVu();
initDoc();
initTape();
initSnd();
initKeys();
initErr();
